# This is a basic workflow to help you get started with Actions

name: Vale-Linting-Assignment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Vale-Linting:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Run Vale
      - name: Run Vale on markdown files
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: '**/*.md'
          fail_on_error: false  # Vale warnings but don’t fail

      # Step 3: Broken Link Checker
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exit-zero './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
