name: Vale Linting Assignment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Run Vale
      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          files: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Setup Node.js (needed for markdown-link-check)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 4: Install markdown-link-check
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      # Step 5: Run markdown-link-check (warn only)
      - name: Check Markdown Links
        run: |
          find . -name "*.md" -print0 | xargs -0 -n1 markdown-link-check -q
        continue-on-error: true
